site_name: Unnamed (SC) Datapack Specification
site_url: https://sixslime.github.io/unnamed-sc-doc
theme:
  name: material
  font:
    text: "Atkinson Hyperlegible"
    code: "JetBrains Mono"
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: indigo
      accent: cyan

    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: cyan
      accent: deep purple

  features:
    - navigation.instant
    - navigation.path
    - navigation.indexes

nav:
  - What Is SC?: index.md
  - Guide:
    - Converting Your Datapack:
      - guide/converting/index.md
    - SlimeCore In-Depth:
      - guide/slimecore/index.md
  - Quick Reference:
    - Foo: guide/quickref/foo.md
  - Why SC?: why.md
  - About: meta.md
