site_name: Unnamed (SC) Datapack Specification
site_url: https://sixslime.github.io/unnamed-sc-doc
theme:
  name: material
  font:
    text: "Atkinson Hyperlegible"
    code: "JetBrains Mono"
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: indigo
      accent: teal

    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: cyan
      accent: deep purple

  features:
    - navigation.instant
    - navigation.path
    - navigation.indexes
    - navigation.footer
nav:
  - What Is SC?: index.md
  - Terminology: definitions.md
  - Guide:
    - Converting Your Datapack:
      - Converting Your Datapack: guide/converting/index.md
      - 'Primary Namespace': guide/converting/namespace.md
      - 'Entrypoints': guide/converting/entrypoints.md
      - 'SlimeCore': guide/converting/slimecore.md
      - Pack Manifest: guide/converting/manifest.md
    - SlimeCore In-Depth:
      - SlimeCore In-Depth: guide/slimecore/index.md
  - Reference:
    - Foo: guide/reference/foo.md
  - Why SC?: why.md
  - About: meta.md
